// flow-typed signature: d0dba8025cbe2968ec7c9cdda976f02a
// flow-typed version: <<STUB>>/@walletconnect/web3-provider_v^1.7.7/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@walletconnect/web3-provider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@walletconnect/web3-provider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@walletconnect/web3-provider/dist/cjs' {
  declare module.exports: any;
}

declare module '@walletconnect/web3-provider/dist/esm' {
  declare module.exports: any;
}

declare module '@walletconnect/web3-provider/dist/umd/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@walletconnect/web3-provider/dist/cjs/index' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/dist/cjs'>;
}
declare module '@walletconnect/web3-provider/dist/cjs/index.js' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/dist/cjs'>;
}
declare module '@walletconnect/web3-provider/dist/esm/index' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/dist/esm'>;
}
declare module '@walletconnect/web3-provider/dist/esm/index.js' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/dist/esm'>;
}
declare module '@walletconnect/web3-provider/dist/umd/index.min.js' {
  declare module.exports: $Exports<'@walletconnect/web3-provider/dist/umd/index.min'>;
}
