// flow-typed signature: 8599becbfb4b64344b49b790332c94f5
// flow-typed version: <<STUB>>/authereum_v^0.1.14/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'authereum'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'authereum' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'authereum/authereum' {
  declare module.exports: any;
}

declare module 'authereum/dist/AuthereumProvider' {
  declare module.exports: any;
}

declare module 'authereum/dist/AuthereumSDK' {
  declare module.exports: any;
}

declare module 'authereum/dist/AuthereumSigner' {
  declare module.exports: any;
}

declare module 'authereum/dist/config' {
  declare module.exports: any;
}

declare module 'authereum/dist' {
  declare module.exports: any;
}

declare module 'authereum/dist/LoopringProvider' {
  declare module.exports: any;
}

declare module 'authereum/dist/StarkWareProvider' {
  declare module.exports: any;
}

declare module 'authereum/dist/utils' {
  declare module.exports: any;
}

declare module 'authereum/dist/version' {
  declare module.exports: any;
}

declare module 'authereum/dist/ZkSyncProvider' {
  declare module.exports: any;
}

declare module 'authereum/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'authereum/authereum.js' {
  declare module.exports: $Exports<'authereum/authereum'>;
}
declare module 'authereum/dist/AuthereumProvider.js' {
  declare module.exports: $Exports<'authereum/dist/AuthereumProvider'>;
}
declare module 'authereum/dist/AuthereumSDK.js' {
  declare module.exports: $Exports<'authereum/dist/AuthereumSDK'>;
}
declare module 'authereum/dist/AuthereumSigner.js' {
  declare module.exports: $Exports<'authereum/dist/AuthereumSigner'>;
}
declare module 'authereum/dist/config.js' {
  declare module.exports: $Exports<'authereum/dist/config'>;
}
declare module 'authereum/dist/index' {
  declare module.exports: $Exports<'authereum/dist'>;
}
declare module 'authereum/dist/index.js' {
  declare module.exports: $Exports<'authereum/dist'>;
}
declare module 'authereum/dist/LoopringProvider.js' {
  declare module.exports: $Exports<'authereum/dist/LoopringProvider'>;
}
declare module 'authereum/dist/StarkWareProvider.js' {
  declare module.exports: $Exports<'authereum/dist/StarkWareProvider'>;
}
declare module 'authereum/dist/utils.js' {
  declare module.exports: $Exports<'authereum/dist/utils'>;
}
declare module 'authereum/dist/version.js' {
  declare module.exports: $Exports<'authereum/dist/version'>;
}
declare module 'authereum/dist/ZkSyncProvider.js' {
  declare module.exports: $Exports<'authereum/dist/ZkSyncProvider'>;
}
declare module 'authereum/jest.config.js' {
  declare module.exports: $Exports<'authereum/jest.config'>;
}
