// flow-typed signature: c620000e32b0ebfaf47e67429bb2ee61
// flow-typed version: <<STUB>>/ethers_v^5.5.4/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethers/dist/ethers.esm' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers.esm.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers.umd' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers.umd.min' {
  declare module.exports: any;
}

declare module 'ethers/lib.esm/_version' {
  declare module.exports: any;
}

declare module 'ethers/lib.esm/ethers' {
  declare module.exports: any;
}

declare module 'ethers/lib.esm' {
  declare module.exports: any;
}

declare module 'ethers/lib.esm/utils' {
  declare module.exports: any;
}

declare module 'ethers/lib/_version' {
  declare module.exports: any;
}

declare module 'ethers/lib/ethers' {
  declare module.exports: any;
}

declare module 'ethers/lib' {
  declare module.exports: any;
}

declare module 'ethers/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethers/dist/ethers.esm.js' {
  declare module.exports: $Exports<'ethers/dist/ethers.esm'>;
}
declare module 'ethers/dist/ethers.esm.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers.esm.min'>;
}
declare module 'ethers/dist/ethers.umd.js' {
  declare module.exports: $Exports<'ethers/dist/ethers.umd'>;
}
declare module 'ethers/dist/ethers.umd.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers.umd.min'>;
}
declare module 'ethers/lib.esm/_version.js' {
  declare module.exports: $Exports<'ethers/lib.esm/_version'>;
}
declare module 'ethers/lib.esm/ethers.js' {
  declare module.exports: $Exports<'ethers/lib.esm/ethers'>;
}
declare module 'ethers/lib.esm/index' {
  declare module.exports: $Exports<'ethers/lib.esm'>;
}
declare module 'ethers/lib.esm/index.js' {
  declare module.exports: $Exports<'ethers/lib.esm'>;
}
declare module 'ethers/lib.esm/utils.js' {
  declare module.exports: $Exports<'ethers/lib.esm/utils'>;
}
declare module 'ethers/lib/_version.js' {
  declare module.exports: $Exports<'ethers/lib/_version'>;
}
declare module 'ethers/lib/ethers.js' {
  declare module.exports: $Exports<'ethers/lib/ethers'>;
}
declare module 'ethers/lib/index' {
  declare module.exports: $Exports<'ethers/lib'>;
}
declare module 'ethers/lib/index.js' {
  declare module.exports: $Exports<'ethers/lib'>;
}
declare module 'ethers/lib/utils.js' {
  declare module.exports: $Exports<'ethers/lib/utils'>;
}
