// flow-typed signature: 18c3ec6dcb5017213292478e9efb27a2
// flow-typed version: <<STUB>>/metamask-react_v^2.3.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metamask-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metamask-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'metamask-react/lib' {
  declare module.exports: any;
}

declare module 'metamask-react/lib/metamask-context' {
  declare module.exports: any;
}

declare module 'metamask-react/lib/metamask-provider' {
  declare module.exports: any;
}

declare module 'metamask-react/lib/reducer' {
  declare module.exports: any;
}

declare module 'metamask-react/lib/use-metamask' {
  declare module.exports: any;
}

declare module 'metamask-react/lib/utils/useSafeDispatch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'metamask-react/lib/index' {
  declare module.exports: $Exports<'metamask-react/lib'>;
}
declare module 'metamask-react/lib/index.js' {
  declare module.exports: $Exports<'metamask-react/lib'>;
}
declare module 'metamask-react/lib/metamask-context.js' {
  declare module.exports: $Exports<'metamask-react/lib/metamask-context'>;
}
declare module 'metamask-react/lib/metamask-provider.js' {
  declare module.exports: $Exports<'metamask-react/lib/metamask-provider'>;
}
declare module 'metamask-react/lib/reducer.js' {
  declare module.exports: $Exports<'metamask-react/lib/reducer'>;
}
declare module 'metamask-react/lib/use-metamask.js' {
  declare module.exports: $Exports<'metamask-react/lib/use-metamask'>;
}
declare module 'metamask-react/lib/utils/useSafeDispatch.js' {
  declare module.exports: $Exports<'metamask-react/lib/utils/useSafeDispatch'>;
}
