// flow-typed signature: 54393c0ed11f79a1f43e4793efacd63b
// flow-typed version: <<STUB>>/react-async_v^10.0.1/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async/dist-node' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/Async' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/globalScope' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/helpers' {
  declare module.exports: any;
}

declare module 'react-async/dist-src' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/propTypes' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/reducer' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/status' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/types' {
  declare module.exports: any;
}

declare module 'react-async/dist-src/useAsync' {
  declare module.exports: any;
}

declare module 'react-async/dist-umd' {
  declare module.exports: any;
}

declare module 'react-async/dist-web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async/dist-node/index' {
  declare module.exports: $Exports<'react-async/dist-node'>;
}
declare module 'react-async/dist-node/index.js' {
  declare module.exports: $Exports<'react-async/dist-node'>;
}
declare module 'react-async/dist-src/Async.js' {
  declare module.exports: $Exports<'react-async/dist-src/Async'>;
}
declare module 'react-async/dist-src/globalScope.js' {
  declare module.exports: $Exports<'react-async/dist-src/globalScope'>;
}
declare module 'react-async/dist-src/helpers.js' {
  declare module.exports: $Exports<'react-async/dist-src/helpers'>;
}
declare module 'react-async/dist-src/index' {
  declare module.exports: $Exports<'react-async/dist-src'>;
}
declare module 'react-async/dist-src/index.js' {
  declare module.exports: $Exports<'react-async/dist-src'>;
}
declare module 'react-async/dist-src/propTypes.js' {
  declare module.exports: $Exports<'react-async/dist-src/propTypes'>;
}
declare module 'react-async/dist-src/reducer.js' {
  declare module.exports: $Exports<'react-async/dist-src/reducer'>;
}
declare module 'react-async/dist-src/status.js' {
  declare module.exports: $Exports<'react-async/dist-src/status'>;
}
declare module 'react-async/dist-src/types.js' {
  declare module.exports: $Exports<'react-async/dist-src/types'>;
}
declare module 'react-async/dist-src/useAsync.js' {
  declare module.exports: $Exports<'react-async/dist-src/useAsync'>;
}
declare module 'react-async/dist-umd/index' {
  declare module.exports: $Exports<'react-async/dist-umd'>;
}
declare module 'react-async/dist-umd/index.js' {
  declare module.exports: $Exports<'react-async/dist-umd'>;
}
declare module 'react-async/dist-web/index' {
  declare module.exports: $Exports<'react-async/dist-web'>;
}
declare module 'react-async/dist-web/index.js' {
  declare module.exports: $Exports<'react-async/dist-web'>;
}
