// flow-typed signature: d11cc8d9c135ac33cfd8f71170627ce8
// flow-typed version: <<STUB>>/stream-http_v^3.2.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-http/lib/capability' {
  declare module.exports: any;
}

declare module 'stream-http/lib/request' {
  declare module.exports: any;
}

declare module 'stream-http/lib/response' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-http/index' {
  declare module.exports: $Exports<'stream-http'>;
}
declare module 'stream-http/index.js' {
  declare module.exports: $Exports<'stream-http'>;
}
declare module 'stream-http/lib/capability.js' {
  declare module.exports: $Exports<'stream-http/lib/capability'>;
}
declare module 'stream-http/lib/request.js' {
  declare module.exports: $Exports<'stream-http/lib/request'>;
}
declare module 'stream-http/lib/response.js' {
  declare module.exports: $Exports<'stream-http/lib/response'>;
}
