// flow-typed signature: 0be8116f7e56c86481f61f018d07f36b
// flow-typed version: <<STUB>>/web3modal_v^1.9.6/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3modal/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3modal/dist/index' {
  declare module.exports: $Exports<'web3modal/dist'>;
}
declare module 'web3modal/dist/index.js' {
  declare module.exports: $Exports<'web3modal/dist'>;
}
