// flow-typed signature: 6bf8f6be3a60e7c694d940f37804eb46
// flow-typed version: <<STUB>>/web3_v^1.7.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3/dist/web3.min' {
  declare module.exports: any;
}

declare module 'web3/lib' {
  declare module.exports: any;
}

declare module 'web3/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3/dist/web3.min.js' {
  declare module.exports: $Exports<'web3/dist/web3.min'>;
}
declare module 'web3/lib/index' {
  declare module.exports: $Exports<'web3/lib'>;
}
declare module 'web3/lib/index.js' {
  declare module.exports: $Exports<'web3/lib'>;
}
declare module 'web3/src/index' {
  declare module.exports: $Exports<'web3/src'>;
}
declare module 'web3/src/index.js' {
  declare module.exports: $Exports<'web3/src'>;
}
