// flow-typed signature: 35694036486c87d4d8e4962aa91dc0d6
// flow-typed version: <<STUB>>/@coinbase/wallet-sdk_v^3.0.7/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@coinbase/wallet-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@coinbase/wallet-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@coinbase/wallet-sdk/dist/CoinbaseWalletSDK' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/icons/globe-icon-svg' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/icons/link-icon-svg' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/icons/lock-icon-svg' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/icons/QRLogo' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/LinkDialog-css' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/LinkDialog' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/LinkFlow' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/QRCode' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/Snackbar-css' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/Snackbar' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/Spinner-css' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/Spinner' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/TryExtensionLinkDialog-css' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/components/TryExtensionLinkDialog' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/connection/ClientMessage' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/connection/EventListener' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/connection/RxWebSocket' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/connection/ServerMessage' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/connection/SessionConfig' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/connection/WalletSDKConnection' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/EthereumChain' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/lib/cssReset-css' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/lib/cssReset' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/lib/ScopedLocalStorage' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/provider/FilterPolyfill' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/provider/JSONRPC' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/provider/SubscriptionManager' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/provider/WalletSDKUI' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/provider/WalletUI' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/provider/Web3Provider' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/aes256gcm' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/EthereumTransactionParams' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/RelayMessage' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/Session' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/WalletSDKRelay' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/WalletSDKRelayAbstract' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/WalletSDKRelayEventManager' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/Web3Method' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/Web3Request' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/Web3RequestCanceledMessage' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/Web3RequestMessage' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/Web3Response' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/relay/Web3ResponseMessage' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/types' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/util' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/abi' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/util' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/keccak' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/shake' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak-state-reference' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak-state-unroll' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/vendor-js/qrcode-svg' {
  declare module.exports: any;
}

declare module '@coinbase/wallet-sdk/dist/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@coinbase/wallet-sdk/dist/CoinbaseWalletSDK.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/CoinbaseWalletSDK'>;
}
declare module '@coinbase/wallet-sdk/dist/components/icons/globe-icon-svg.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/icons/globe-icon-svg'>;
}
declare module '@coinbase/wallet-sdk/dist/components/icons/link-icon-svg.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/icons/link-icon-svg'>;
}
declare module '@coinbase/wallet-sdk/dist/components/icons/lock-icon-svg.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/icons/lock-icon-svg'>;
}
declare module '@coinbase/wallet-sdk/dist/components/icons/QRLogo.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/icons/QRLogo'>;
}
declare module '@coinbase/wallet-sdk/dist/components/LinkDialog-css.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/LinkDialog-css'>;
}
declare module '@coinbase/wallet-sdk/dist/components/LinkDialog.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/LinkDialog'>;
}
declare module '@coinbase/wallet-sdk/dist/components/LinkFlow.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/LinkFlow'>;
}
declare module '@coinbase/wallet-sdk/dist/components/QRCode.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/QRCode'>;
}
declare module '@coinbase/wallet-sdk/dist/components/Snackbar-css.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/Snackbar-css'>;
}
declare module '@coinbase/wallet-sdk/dist/components/Snackbar.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/Snackbar'>;
}
declare module '@coinbase/wallet-sdk/dist/components/Spinner-css.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/Spinner-css'>;
}
declare module '@coinbase/wallet-sdk/dist/components/Spinner.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/Spinner'>;
}
declare module '@coinbase/wallet-sdk/dist/components/TryExtensionLinkDialog-css.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/TryExtensionLinkDialog-css'>;
}
declare module '@coinbase/wallet-sdk/dist/components/TryExtensionLinkDialog.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/components/TryExtensionLinkDialog'>;
}
declare module '@coinbase/wallet-sdk/dist/connection/ClientMessage.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/connection/ClientMessage'>;
}
declare module '@coinbase/wallet-sdk/dist/connection/EventListener.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/connection/EventListener'>;
}
declare module '@coinbase/wallet-sdk/dist/connection/RxWebSocket.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/connection/RxWebSocket'>;
}
declare module '@coinbase/wallet-sdk/dist/connection/ServerMessage.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/connection/ServerMessage'>;
}
declare module '@coinbase/wallet-sdk/dist/connection/SessionConfig.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/connection/SessionConfig'>;
}
declare module '@coinbase/wallet-sdk/dist/connection/WalletSDKConnection.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/connection/WalletSDKConnection'>;
}
declare module '@coinbase/wallet-sdk/dist/EthereumChain.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/EthereumChain'>;
}
declare module '@coinbase/wallet-sdk/dist/index' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist'>;
}
declare module '@coinbase/wallet-sdk/dist/index.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist'>;
}
declare module '@coinbase/wallet-sdk/dist/lib/cssReset-css.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/lib/cssReset-css'>;
}
declare module '@coinbase/wallet-sdk/dist/lib/cssReset.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/lib/cssReset'>;
}
declare module '@coinbase/wallet-sdk/dist/lib/ScopedLocalStorage.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/lib/ScopedLocalStorage'>;
}
declare module '@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/provider/CoinbaseWalletProvider'>;
}
declare module '@coinbase/wallet-sdk/dist/provider/FilterPolyfill.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/provider/FilterPolyfill'>;
}
declare module '@coinbase/wallet-sdk/dist/provider/JSONRPC.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/provider/JSONRPC'>;
}
declare module '@coinbase/wallet-sdk/dist/provider/SubscriptionManager.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/provider/SubscriptionManager'>;
}
declare module '@coinbase/wallet-sdk/dist/provider/WalletSDKUI.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/provider/WalletSDKUI'>;
}
declare module '@coinbase/wallet-sdk/dist/provider/WalletUI.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/provider/WalletUI'>;
}
declare module '@coinbase/wallet-sdk/dist/provider/Web3Provider.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/provider/Web3Provider'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/aes256gcm.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/aes256gcm'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/EthereumTransactionParams.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/EthereumTransactionParams'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/RelayMessage.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/RelayMessage'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/Session.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/Session'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/WalletSDKRelay.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/WalletSDKRelay'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/WalletSDKRelayAbstract.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/WalletSDKRelayAbstract'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/WalletSDKRelayEventManager.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/WalletSDKRelayEventManager'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/Web3Method.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/Web3Method'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/Web3Request.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/Web3Request'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/Web3RequestCanceledMessage.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/Web3RequestCanceledMessage'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/Web3RequestMessage.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/Web3RequestMessage'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/Web3Response.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/Web3Response'>;
}
declare module '@coinbase/wallet-sdk/dist/relay/Web3ResponseMessage.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/relay/Web3ResponseMessage'>;
}
declare module '@coinbase/wallet-sdk/dist/types.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/types'>;
}
declare module '@coinbase/wallet-sdk/dist/util.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/util'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/abi.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/abi'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/index' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/index.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/util.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/eth-eip712-util/util'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/index' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/index.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/index' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/index.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/keccak.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/keccak'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/shake.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/api/shake'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak-state-reference.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak-state-reference'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak-state-unroll.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak-state-unroll'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/keccak/lib/keccak'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/qrcode-svg/index' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/qrcode-svg'>;
}
declare module '@coinbase/wallet-sdk/dist/vendor-js/qrcode-svg/index.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/vendor-js/qrcode-svg'>;
}
declare module '@coinbase/wallet-sdk/dist/version.js' {
  declare module.exports: $Exports<'@coinbase/wallet-sdk/dist/version'>;
}
