// flow-typed signature: adcb1d6c05c85ad303273451ba2f2eb1
// flow-typed version: <<STUB>>/@toruslabs/torus-embed_v^1.22.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@toruslabs/torus-embed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@toruslabs/torus-embed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@toruslabs/torus-embed/dist/torus-bundled.cjs' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/torus.cjs' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/torus.esm' {
  declare module.exports: any;
}

declare module '@toruslabs/torus-embed/dist/torus.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@toruslabs/torus-embed/dist/torus-bundled.cjs.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/torus-bundled.cjs'>;
}
declare module '@toruslabs/torus-embed/dist/torus.cjs.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/torus.cjs'>;
}
declare module '@toruslabs/torus-embed/dist/torus.esm.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/torus.esm'>;
}
declare module '@toruslabs/torus-embed/dist/torus.umd.min.js' {
  declare module.exports: $Exports<'@toruslabs/torus-embed/dist/torus.umd.min'>;
}
